### ISSUE TITLE
Move this repo, and the widget repositories to an organization

### ISSUE THREAD

**Issue by ChipWolf** [rcon-web-admin/rcon-web-admin#5]
I believe it would be useful to fork all the core widgets from @brainfoolong so we can remove the project discontinued notice and continue to iterate.

![](https://i.imgur.com/Qx6Bdfv.png)

I would suggest moving this repo, and the widget forks into an 'rcon-web-admin' organization to allow for these projects to be clearly grouped, and to allow for extended collaboration.

**Comment by lacaulac** [comment]
Definitely sounds like a better way to handle this. I'm gonna create the org and move the current repo into it.
